
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-renuvo-store-tls
  namespace: argocd
spec:
  secretName: server-renuvo-store-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.renuvo.store
  dnsNames:
  - argo.renuvo.store